---
abstract: 'abstract class for Date::Holidays::* packages'
author:
  - 'Jonas B. Nielsen <jonasbn@cpan.org>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Module::Build: 0.30
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
  Module::Build: 0.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Date-Holidays-Abstract
requires:
  Class::Virtually::Abstract: 0
  Test::Harness: 0
  Test::More: 0
  perl: 5.006
resources:
  homepage: http://search.cpan.org/dist/Date-Holidays-Abstract/
  repository: git://github.com/gitpan/Date-Holidays-Abstract.git
version: 0.07
